### ISSUE TITLE
Can pretty_html_table provide the option to return <class 'pandas.io.formats.style.Styler'> rather than <class 'str'>

### ISSUE THREAD

**Issue by hao-lh** [sbi-rviot/ph_table#8]
I have to admit `pretty_html_table.build_table()` is pretty easy to use when users wanted to output pandas dataframe to html file, especially some advanced styling control not easy or even not able to achieve on terminal/console, thanks a lot for your contributions!

However, I find pretty_html_table hard to combine with `<class 'pandas.io.formats.style.Styler'>` which accepts `pandas.dataframe` as input and output `pandas.io.formats.style.Styler`, while pretty_html_table also accepts `pandas.dataframe` as input while output `str`. So my question is any option to combine these two as users may need some advanced styling control for dataframe before outputting to html file.

For example, I wanted to highlight cells contained in a list for pandas specific column, simplified code is provided as follows. Please provide suggestions and help, thanks!

```python
import pandas as pd
import os
import webbrowser

def write_data_to_file(filename, content):
    file = open(filename, mode='w')
    file.write(content)
    file.close()


def highlight_hot_color(col):
    hot_color = ['red', 'yellow', 'orange']
    check = [item in hot_color for item in col]
    return ['background-color: yellow' if v else '' for v in check]

if __name__ == '__main__':
    data_frame = pd.DataFrame([['Allen', 'red', 20], ['Tom', 'yellow', 30], ['Jack', 'blue', 40], ['Bob', 'grey', 50]], 
        columns=['name', 'color', 'age'])
    data_frame.style.apply(highlight_hot_color, subset=['color'])

    html = data_frame.to_html(index=False)
    file_name = 'test.html'
    path_name = os.path.abspath(file_name)
    url = 'file://' + path_name
    write_data_to_file(path_name, html)
    webbrowser.open(url)
```

**Comment by sbi-rviot** [comment]
Clear request - will take a look.

**Comment by sbi-rviot** [comment]
Hello @hao-lh,
Sorry for the delays.

The issue with emails, which is why we created this library in the first place, is that only inline css is accepted when you want to send a table via email. This library makes table prettier by applying a "nice" style to each of the row in the table you have individually.

In order to take into account further cell formatting, we could build an additional control, with the rule(s) and the column to apply it to. I did not have time to put my head back into it. If you wish to contribute your code, please do so and I'll review it.

**Comment by sbi-rviot** [comment]
I am adding it to the backlog. Closing the issue (over 30 days)
